### ISSUE TITLE
Enable the rss feed

### ISSUE THREAD

**Issue by oresk** [DNedic/dnedic.github.io#1]
Nice and exhaustive blog post!

Could you please turn on the rss feed ?
[Seems](https://www.getzola.org/documentation/templates/feeds/) that adding `generate_feed = true` to the `config.toml` should be enough.

**Comment by DNedic** [comment]
I'm really glad you like the blogpost, i've enabled the feed, please let me know if it works for you.

**Comment by oresk** [comment]
Works now!
